version: '3.4'
networks:
  backend:

services:
  es.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: es.db
    ports:
      - "8001:1433" 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=H@med1369
    networks:
      - backend
    volumes:
      - "./data:/var/opt/mssql/data" 
  es.presentation:
    image: ${DOCKER_REGISTRY-}espresentation 
    build:
      context: .
      dockerfile: ES.Presentation/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=es.db
      - DB_NAME=Ecommerce
      - DB_SA_PASSWORD=H@med1369
    depends_on:
      - es.db
    deploy:
      replicas: 3
  es.redis:
    image: redis
    container_name: es.redis
    ports:
      - 8005:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CONNECTION_STRING=redis:8005
  es.balancer:
    container_name: es.balancer
    image: nginx:latest
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    ports:
      -  "8004:80"
    networks:
      - backend
    depends_on:
      - es.presentation